# Generated by Django 4.0.4 on 2022-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(default='games', max_length=255),
            preserve_default=False,
        ),
    ]
