# Generated by Django 4.0.4 on 2022-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=555)),
                ('image', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PostGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_players', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=555)),
                ('image', models.ImageField(upload_to='images_post')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
