# Generated by Django 4.0.4 on 2022-05-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_postbio_postgames_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgames',
            name='date',
        ),
    ]
