# Generated by Django 4.0.4 on 2022-05-24 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_remove_postgames_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgames',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
