# Generated by Django 4.0.4 on 2022-05-25 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_postgames_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbio',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='postbio',
            name='image',
            field=models.ImageField(upload_to='images_post'),
        ),
    ]
