# Generated by Django 4.0.4 on 2022-05-25 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_postbio_date_alter_postbio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPuzzles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=555)),
                ('image', models.ImageField(upload_to='images_post')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
