# Generated by Django 4.0.4 on 2022-05-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_postgames_author_alter_postgames_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgames',
            name='author',
        ),
    ]
