# Generated by Django 4.0.4 on 2022-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_postbio_author_postpuzzles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpuzzles',
            name='content',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='Contenido adicional'),
        ),
        migrations.AlterField(
            model_name='postpuzzles',
            name='image',
            field=models.ImageField(upload_to='images_post', verbose_name='Imágen del post'),
        ),
        migrations.AlterField(
            model_name='postpuzzles',
            name='solution',
            field=models.CharField(max_length=255, verbose_name='Solución del problema'),
        ),
        migrations.AlterField(
            model_name='postpuzzles',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
