# Generated by Django 4.0.4 on 2022-05-26 23:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0014_alter_postpuzzles_content_alter_postpuzzles_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbio',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
