# Generated by Django 4.0.4 on 2022-05-27 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0015_alter_postbio_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbio',
            name='content',
            field=models.CharField(max_length=555),
        ),
        migrations.CreateModel(
            name='CommentGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsGames', to='Posts.postgames')),
            ],
        ),
    ]
