# Generated by Django 4.0.4 on 2022-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0017_remove_commentgames_commenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentgames',
            name='commenter_id',
        ),
        migrations.AddField(
            model_name='commentgames',
            name='commenter',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
