# Generated by Django 4.0.4 on 2022-05-27 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0018_remove_commentgames_commenter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentgames',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
