# Generated by Django 4.0.4 on 2022-05-27 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0020_commentbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbio',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsBio', to='Posts.postbio'),
        ),
    ]
