# Generated by Django 4.0.4 on 2022-05-28 02:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0021_alter_commentbio_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbio',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
