# Generated by Django 4.0.4 on 2022-05-28 03:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0022_alter_postbio_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbio',
            name='likes',
            field=models.ManyToManyField(related_name='blog_postsBio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postgames',
            name='likes',
            field=models.ManyToManyField(related_name='blog_postsGames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postpuzzles',
            name='likes',
            field=models.ManyToManyField(related_name='blog_postsPuzzles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postgames',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpuzzles',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido adicional'),
        ),
    ]
