# Generated by Django 4.0.4 on 2022-06-05 03:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0026_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbio',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='postbio',
            name='image',
            field=models.ImageField(upload_to='images_post', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='postbio',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='postgames',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='postgames',
            name='result',
            field=models.IntegerField(choices=[(1, '1-0'), (2, '0-1'), (3, '1/2-1/2')], verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='postgames',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Lugar y fecha'),
        ),
        migrations.AlterField(
            model_name='postgames',
            name='title_players',
            field=models.CharField(max_length=255, verbose_name='Jugadores'),
        ),
    ]
